[build]
    command = "make build"

[build.environment]
    # Change this path with the path to your repository
    GO_IMPORT_PATH = "github.com/cbosss/functions-playground"

[[redirects]]
    from = "/images/*"
    to = "/.netlify/functions/resize"
    status = 200

[[redirects]]
    from = "/easter.js"
    to = "/empty.js"
    status = 200
    force = true